# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReacttiveObjC-MVVM-tableview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReacttiveObjC-MVVM-tableview
    pod 'ReactiveObjC'
    pod 'MJRefresh'

  target 'ReacttiveObjC-MVVM-tableviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReacttiveObjC-MVVM-tableviewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
